// Package docs renders the check documentation from the check table.
//
// The facts on a page are generated rather than written, because they are
// already in internal/lint/checks.go and the resolver reads them from there.
// A page stating a default by hand can be perfectly consistent with itself
// and still describe a tool that behaves differently, and the gate that
// regenerates and diffs would certify it (spec 7.8).
//
// What is not generated is everything worth reading: why a check exists, what
// breaks when it fires, and how to fix it. That lives between the markers'
// outside, hand written, and the generator never touches it.
package docs

import (
	"fmt"
	"sort"
	"strings"

	"github.com/dennisme/clickhouse-ruler/internal/lint"
)

//go:generate go run ./gen -out ../../docs/checks

// Pages are the files the checks are documented in, in the order the index
// lists them.
var Pages = []string{"rule.md", "source.md", "policy.md"}

// Markers fence the generated region. A reader who edits inside them loses
// the edit on the next generate, so the opening one says so.
const (
	markerStart = "<!-- generated by `just generate`: do not edit below -->"
	markerEnd   = "<!-- end generated -->"
)

// Facts renders the table of what every check on a page ships as.
func Facts(page string) string {
	var sb strings.Builder

	sb.WriteString("| Check | Severity | Keys | Spec |\n")
	sb.WriteString("| --- | --- | --- | --- |\n")

	for _, c := range lint.All() {
		if lint.DocsPage(c.Name) != page {
			continue
		}
		fmt.Fprintf(&sb, "| [`%s`](#%s) | %s | %s | %s |\n",
			c.Name, lint.DocsAnchor(c.Name), severity(c), keys(c), specLink(c))
	}
	return sb.String()
}

// Index renders the whole index page, which is generated end to end: it is a
// list of what exists, and there is nothing to say about it that the table
// does not already carry.
func Index() string {
	var sb strings.Builder

	sb.WriteString("# Checks\n\n")
	sb.WriteString("Every check this ruler can report, what it ships as, and where it is explained.\n\n")
	sb.WriteString("Generated from the check table in `internal/lint/checks.go`. ")
	sb.WriteString("Edit the table, then run `just generate`.\n\n")
	sb.WriteString("| Check | Severity | What it reports |\n")
	sb.WriteString("| --- | --- | --- |\n")

	for _, c := range lint.All() {
		fmt.Fprintf(&sb, "| [`%s`](%s#%s) | %s | %s |\n",
			c.Name, lint.DocsPage(c.Name), lint.DocsAnchor(c.Name), severity(c), c.Summary)
	}
	return sb.String()
}

// severity says what an operator can do about a check, not only what it ships
// as: "fixed" is the part that answers "can I turn this off".
func severity(c lint.Check) string {
	if c.Fixed {
		return "fixed, always `error`"
	}
	return fmt.Sprintf("`%s` by default", c.Default)
}

func keys(c lint.Check) string {
	if len(c.Keys) == 0 {
		switch c.List {
		case lint.ListAllowlist:
			return "an allowlist, shipped empty"
		case lint.ListNone, lint.ListRequired, lint.ListCeiling:
			return "none"
		}
		return "none"
	}

	quoted := make([]string, 0, len(c.Keys))
	for _, k := range c.Keys {
		quoted = append(quoted, "`"+k+"`")
	}
	return fmt.Sprintf("%s: %s", listName(c), strings.Join(quoted, ", "))
}

// listName describes what a check ships in its list. A ceiling list can carry
// flags as well, and calling one of those a ceiling would send a reader looking
// for a number it does not take (spec 7.7). What is named is what is shipped: a
// flag a check merely permits is documented in its own section, not here, or the
// table would read as though it were set.
func listName(c lint.Check) string {
	if c.List != lint.ListCeiling {
		return listKind(c.List)
	}
	for _, k := range c.Keys {
		if !strings.Contains(k, ":") {
			return "ceilings and flags"
		}
	}
	return listKind(c.List)
}

// listKind names the direction a scope combines the list in, because that is
// what decides whether an operator can shorten it (spec 7.7).
func listKind(l lint.ListKind) string {
	switch l {
	case lint.ListRequired:
		return "required"
	case lint.ListAllowlist:
		return "allowlist"
	case lint.ListCeiling:
		return "ceilings"
	case lint.ListNone:
		return ""
	}
	return ""
}

// specLink points at the spec on GitHub rather than at a relative path. The
// spec is not part of the published site, so `../../spec.md` resolves on a
// checkout and 404s everywhere the findings actually send people.
func specLink(c lint.Check) string {
	return fmt.Sprintf("[%s](https://github.com/dennisme/clickhouse-ruler/blob/main/spec.md)", c.Spec)
}

// Apply replaces a page's generated region, leaving every other byte alone.
//
// An error rather than an append when the markers are missing: a page that
// lost them would otherwise grow a second table on every run.
func Apply(page, content string) (string, error) {
	start := strings.Index(content, markerStart)
	end := strings.Index(content, markerEnd)

	switch {
	case start < 0 || end < 0:
		return "", fmt.Errorf("%s has no generated region, expected %s ... %s", page, markerStart, markerEnd)
	case end < start:
		return "", fmt.Errorf("%s closes its generated region before it opens", page)
	}

	return content[:start] + markerStart + "\n\n" + Facts(page) + "\n" + content[end:], nil
}

// Headings lists the check headings a page carries, in the order they appear,
// with the body that follows each one.
//
// Read back rather than trusted: a heading generated with nothing under it is
// a page that looks documented and says nothing, so the tests need to see
// what is actually there.
func Headings(content string) map[string]string {
	out := map[string]string{}

	var current, pending string
	var body strings.Builder

	flush := func() {
		if current != "" {
			out[current] = strings.TrimSpace(body.String())
		}
		body.Reset()
	}

	for _, line := range strings.Split(content, "\n") {
		if anchorLine(line) {
			// Held rather than written: if a heading follows, this anchor is
			// part of it and not the end of the section above.
			pending = line
			continue
		}
		// A blank line between a held anchor and its heading is the blank line
		// MD022 requires, so it does not end the hold.
		if pending != "" && strings.TrimSpace(line) == "" {
			continue
		}
		if name, ok := checkHeading(line); ok {
			flush()
			current, pending = name, ""
			continue
		}
		if current != "" {
			if pending != "" {
				body.WriteString(pending)
				body.WriteString("\n")
			}
			body.WriteString(line)
			body.WriteString("\n")
		}
		pending = ""
	}
	flush()

	return out
}

// HeadingFor renders a check's section heading, anchor included.
//
// The anchor is an HTML element rather than the `{#id}` attribute list a site
// generator would understand. GitHub Flavored Markdown has no attribute
// lists, so `{#rule-foreign-table}` renders as text inside the heading and
// GitHub slugifies the whole string, leaving every link this repository emits
// pointing at an anchor that does not exist. An `<a id>` is honoured on
// GitHub today and survives being published through a generator later
// (spec 7.8).
//
// A slash cannot be left to the slugifier either way: GitHub drops it rather
// than replacing it, so `rule/foreign-table` would become
// `ruleforeign-table`.
// The blank line between the two is what markdownlint's MD022 wants around a
// heading, and an anchor in its own block is still the anchor of the heading
// that follows it.
func HeadingFor(check string) string {
	return fmt.Sprintf("<a id=%q></a>\n\n### %s", lint.DocsAnchor(check), check)
}

// checkHeading reads a per-check heading.
//
// A namespaced name is the shape being matched, deliberately not membership
// of the table: a section headed with a check that does not exist has to be
// readable here, or the test that reports one would have nothing to find.
func checkHeading(line string) (string, bool) {
	name, ok := strings.CutPrefix(line, "### ")
	if !ok {
		return "", false
	}
	name = strings.TrimSpace(name)
	if _, _, namespaced := strings.Cut(name, "/"); !namespaced {
		return "", false
	}
	return name, true
}

// anchorLine reports whether a line is a section's anchor, which belongs to
// the heading below it rather than to the section above.
func anchorLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	return strings.HasPrefix(trimmed, "<a id=") && strings.HasSuffix(trimmed, "</a>")
}

// CheckedIn returns the checks documented across every page, so a test can
// compare them against the table in both directions.
func CheckedIn(read func(page string) (string, error)) (map[string]string, error) {
	out := map[string]string{}

	for _, page := range Pages {
		content, err := read(page)
		if err != nil {
			return nil, err
		}
		for name, body := range Headings(content) {
			if _, dup := out[name]; dup {
				return nil, fmt.Errorf("%s is documented twice, so one of them is unreachable", name)
			}
			out[name] = body
		}
	}
	return out, nil
}

// Namespaces lists the namespaces a page documents, for the page's own
// introduction.
func Namespaces(page string) []string {
	seen := map[string]bool{}

	for _, c := range lint.All() {
		if lint.DocsPage(c.Name) != page {
			continue
		}
		namespace, _, _ := strings.Cut(c.Name, "/")
		seen[namespace] = true
	}

	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)

	return out
}
